"""Unattended daily catch-up for YouTube transcripts.

Detects the last date that has a `data/raw/<YYYY-MM-DD>/youtube.json`,
computes how many days have gone uncovered, runs the daily collector
once with a lookback wide enough to span the gap (captions-only by
default so the run finishes in minutes), then commits and pushes the
new YouTube-related files to master so the live Streamlit Cloud
dashboard sees them.

Designed for Windows Task Scheduler. The wrapper `scripts/auto_backfill_youtube.bat`
captures stdout/stderr to `data/logs/<date>-yt-backfill.log`.

Honors the user's git-push-guardrails preference: stages only specific
YouTube paths (never `git add -A` or `git add data/`), pull-rebases
first to avoid colliding with the cloud GHA cron at 10 UTC.
"""
import argparse
import logging
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, OSError):
    pass

from collectors.youtube_collector import collect_youtube, save_youtube_results
from config_loader import get_data_dir
from processing.source_health import record_source_result

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
DEFAULT_MAX_GAP_DAYS = 14
FIRST_RUN_GAP_DAYS = 2


def setup_logging(date_str: str) -> logging.Logger:
    log_dir = get_data_dir("logs")
    log_file = log_dir / f"{date_str}-yt-backfill.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        handlers=[
            logging.FileHandler(log_file, encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )
    return logging.getLogger("auto_backfill_yt")


def find_last_covered_date(logger: logging.Logger) -> str | None:
    """Highest YYYY-MM-DD daily dir under data/raw/ with a youtube.json."""
    raw_root = PROJECT_ROOT / "data" / "raw"
    if not raw_root.exists():
        return None
    candidates = []
    for d in raw_root.iterdir():
        if not d.is_dir() or not DATE_RE.match(d.name):
            continue
        yt_path = d / "youtube.json"
        if yt_path.exists():
            candidates.append(d.name)
    if not candidates:
        return None
    last = max(candidates)
    logger.info("Last covered date: %s (from %s)", last, raw_root / last / "youtube.json")
    return last


def compute_lookback_hours(
    today: datetime,
    last_covered: str | None,
    max_gap_days: int,
    logger: logging.Logger,
) -> tuple[int, int]:
    """Return (lookback_hours, effective_gap_days)."""
    if last_covered is None:
        logger.info(
            "No prior daily youtube.json found — treating as first run, "
            "looking back %d days.", FIRST_RUN_GAP_DAYS,
        )
        return FIRST_RUN_GAP_DAYS * 24 + 24, FIRST_RUN_GAP_DAYS

    last_dt = datetime.strptime(last_covered, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    gap_days = (today.date() - last_dt.date()).days
    if gap_days <= 0:
        return 0, 0
    if gap_days > max_gap_days:
        logger.warning(
            "Gap is %d days; capping at --max-gap-days=%d to avoid runaway. "
            "Use the dashboard backfill for older dates.",
            gap_days, max_gap_days,
        )
        gap_days = max_gap_days
    return gap_days * 24 + 24, gap_days


def run_git(cmd: list[str], logger: logging.Logger) -> subprocess.CompletedProcess:
    logger.info("$ %s", " ".join(cmd))
    return subprocess.run(
        cmd, cwd=str(PROJECT_ROOT), capture_output=True, text=True,
    )


def _recover_autostash_conflict(logger: logging.Logger) -> bool:
    """Resolve a conflicted ``--autostash`` re-apply so the commit can proceed.

    ``git pull --rebase --autostash`` re-applies local changes after the
    fast-forward. When the cloud rewrote the same pipeline-generated file
    that also changed locally (data/roster/state.json on 2026-09-09;
    data/source_health.json most mornings, since this script updates it
    too), the apply conflicts: git still exits 0, but leaves those paths
    unmerged and stages every *other* re-applied change. The commit below
    then fails with "unmerged files" — and keeps failing every morning
    until someone resolves it by hand.

    Those files are regenerated by the cloud pipeline, so take origin's copy
    (HEAD after the fast-forward) and drop the accidental staging. The local
    version is still in the autostash entry git keeps (`git stash list`).
    Returns False only if git refuses the resolution.
    """
    unmerged = run_git(["git", "diff", "--name-only", "--diff-filter=U"], logger)
    conflicted = [ln.strip() for ln in unmerged.stdout.splitlines() if ln.strip()]
    if not conflicted:
        return True

    logger.warning(
        "Autostash re-apply conflicted on %s — taking origin's copy "
        "(local version kept in `git stash list`).", ", ".join(conflicted),
    )
    fix = run_git(["git", "checkout", "HEAD", "--"] + conflicted, logger)
    if fix.returncode != 0:
        logger.error(
            "Could not resolve autostash conflict:\nstderr: %s", fix.stderr,
        )
        return False

    # A conflicted apply stages everything else it re-applied (thousands of
    # pruned data/raw deletions, modified data files). Unstage so the commit
    # below stays YouTube-only; the working tree is untouched.
    reset = run_git(["git", "reset", "-q"], logger)
    if reset.returncode != 0:
        logger.error("git reset failed:\nstderr: %s", reset.stderr)
        return False
    return True


_UNTRACKED_COLLISION = "The following untracked working tree files would be overwritten by"


def _parse_untracked_collision(output: str) -> list[str]:
    """Repo-relative paths git named in an untracked-collision abort, if any.

    Git lists them indented between the banner and "Please move or remove
    them". Detection matches the banner prefix rather than the whole sentence
    because the verb varies: a merge says "overwritten by merge", the rebase
    path can say "overwritten by checkout".
    """
    idx = output.find(_UNTRACKED_COLLISION)
    if idx < 0:
        return []
    paths: list[str] = []
    for line in output[idx:].splitlines()[1:]:
        if not line[:1].isspace():
            break
        cleaned = line.strip()
        if cleaned:
            paths.append(cleaned)
    return paths


def _recover_untracked_collision(output: str, logger: logging.Logger) -> bool:
    """Move aside untracked files blocking a pull, so it can be retried once.

    On 2026-09-09 the cloud run force-added a brand-new
    ``data/inactives/espn_athletes.json``. This machine had generated its own
    untracked copy — ``.gitignore`` ignores ``data/inactives/`` locally while
    CI ``git add -f``s it — so the next morning's pull aborted outright and the
    backfill sat on 107 uncommitted transcripts. Every new in-season data file
    the cloud starts tracking can do this again, so it is handled rather than
    merely reported.

    These files are pipeline-generated, so origin's copy wins. The local copy is
    *moved*, never deleted, into a temp directory whose absolute path is logged.
    Returns False when there is nothing of this kind to recover, which leaves
    the caller's existing error handling exactly as it was.
    """
    paths = _parse_untracked_collision(output)
    if not paths:
        return False

    root = PROJECT_ROOT.resolve()
    safe: list[Path] = []
    for rel in paths:
        target = (root / rel).resolve()
        if not target.is_relative_to(root):
            logger.error("Refusing to move %s — it resolves outside the repo.", rel)
            continue
        if target.exists():
            safe.append(target)
    if not safe:
        return False

    backup = Path(tempfile.mkdtemp(prefix="nfl-pull-collision-"))
    logger.warning(
        "Pull blocked by untracked file(s) the cloud now tracks: %s. Taking "
        "origin's copy; the local version is moved to %s.",
        ", ".join(str(p.relative_to(root)) for p in safe), backup,
    )
    for target in safe:
        dest = backup / target.relative_to(root)
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(target), str(dest))
        except OSError as e:
            logger.error("Could not move %s aside: %s", target, e)
            return False
    return True


def push_to_github(today_str: str, logger: logging.Logger) -> bool:
    """Stage YouTube paths only, commit if changed, push to origin master.

    Returns True on success (push happened OR nothing to push), False on
    any git failure. Honors the repo's git-push-guardrails: never stages
    data/ wholesale, never amends, never force-pushes.
    """
    paths = [
        f"data/raw/{today_str}/youtube.json",
        f"data/transcripts/{today_str}",
        "data/youtube_seen.json",
    ]
    existing = [p for p in paths if (PROJECT_ROOT / p).exists()]
    if not existing:
        logger.info("None of the expected YouTube paths exist — nothing to push.")
        return True

    # --autostash so a dirty working tree (e.g. unrelated re-runs of older
    # days that left data/depth_charts/ or data/raw/<other-date>/ files
    # modified) doesn't make rebase abort with "cannot pull with rebase:
    # You have unstaged changes." Git auto-stashes, rebases, then pops.
    pull_cmd = ["git", "pull", "--rebase", "--autostash", "origin", "master"]
    pull = run_git(pull_cmd, logger)
    if pull.returncode != 0:
        # An untracked file the cloud has started tracking aborts the pull
        # before --autostash gets a chance. Move it aside and retry once.
        if not _recover_untracked_collision(pull.stdout + pull.stderr, logger):
            logger.error(
                "git pull --rebase failed:\nstdout: %s\nstderr: %s",
                pull.stdout, pull.stderr,
            )
            return False
        pull = run_git(pull_cmd, logger)
        if pull.returncode != 0:
            logger.error(
                "git pull --rebase still failed after moving collided files "
                "aside:\nstdout: %s\nstderr: %s",
                pull.stdout, pull.stderr,
            )
            return False

    if not _recover_autostash_conflict(logger):
        return False

    # `data/raw/` and `data/transcripts/` are gitignored; the cloud GHA
    # cron uses `git add -f` to force-add them. Mirror that here so the
    # auto-backfill can publish without editing .gitignore.
    add = run_git(["git", "add", "-f", "--"] + existing, logger)
    if add.returncode != 0:
        logger.error("git add failed:\nstderr: %s", add.stderr)
        return False

    diff = run_git(["git", "diff", "--cached", "--quiet"], logger)
    if diff.returncode == 0:
        logger.info("No changes staged — no new transcripts to push.")
        return True

    msg = f"Auto: YouTube transcripts {today_str}"
    commit = run_git(["git", "commit", "-m", msg], logger)
    if commit.returncode != 0:
        logger.error(
            "git commit failed:\nstdout: %s\nstderr: %s",
            commit.stdout, commit.stderr,
        )
        return False

    push = run_git(["git", "push", "origin", "master"], logger)
    if push.returncode != 0:
        logger.error(
            "git push failed:\nstdout: %s\nstderr: %s",
            push.stdout, push.stderr,
        )
        return False

    logger.info("Pushed: %s", msg)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would happen; do no network or git work.",
    )
    parser.add_argument(
        "--no-push", action="store_true",
        help="Collect transcripts but skip the git commit/push step.",
    )
    parser.add_argument(
        "--max-gap-days", type=int, default=DEFAULT_MAX_GAP_DAYS,
        help=(
            f"Cap how many days of gap to attempt to fill in one run "
            f"(default {DEFAULT_MAX_GAP_DAYS}). Larger gaps suggest a "
            f"longer outage and are better handled via the dashboard."
        ),
    )
    parser.add_argument(
        "--enable-whisper", action="store_true",
        help=(
            "Enable Whisper fallback for videos without auto-captions. "
            "Off by default to keep unattended runs short."
        ),
    )
    args = parser.parse_args()

    today = datetime.now(timezone.utc)
    today_str = today.strftime("%Y-%m-%d")
    logger = setup_logging(today_str)

    logger.info("=" * 60)
    logger.info("Auto YouTube backfill: %s", today_str)
    logger.info("  enable_whisper=%s  max_gap_days=%d  dry_run=%s  no_push=%s",
                args.enable_whisper, args.max_gap_days, args.dry_run, args.no_push)
    logger.info("=" * 60)

    last_covered = find_last_covered_date(logger)
    lookback_hours, gap_days = compute_lookback_hours(
        today, last_covered, args.max_gap_days, logger,
    )

    error = ""
    if gap_days == 0:
        # find_last_covered_date looks at local disk, so gap_days==0 just
        # means "today's youtube.json exists locally" — it does NOT mean
        # the file is committed and visible on the cloud. A prior run may
        # have collected data but failed at the push step (e.g. dirty
        # working tree before --autostash was added). Skip collection but
        # still attempt to push, so the cloud catches up.
        logger.info(
            "Already covered locally for %s. Skipping collection but "
            "still attempting push in case prior run failed to publish.",
            today_str,
        )
    else:
        logger.info(
            "Gap: %d days. Lookback window: %d hours. Target date_str: %s",
            gap_days, lookback_hours, today_str,
        )

        if args.dry_run:
            logger.info("--dry-run set; exiting without collection.")
            return 0

        try:
            transcripts = collect_youtube(
                today_str,
                lookback_hours=lookback_hours,
                enable_whisper=args.enable_whisper,
            )
        except Exception as e:
            logger.exception("YouTube collection failed")
            transcripts = []
            error = f"YouTube collection failed: {e}"

        save_youtube_results(transcripts, today_str)
        record_source_result(
            "YouTube", len(transcripts), error=error, low_volume=True,
        )

        logger.info("Wrote %d transcripts for %s.", len(transcripts), today_str)

    if args.no_push:
        logger.info("--no-push set; skipping git push.")
        return 0 if not error else 1

    pushed_ok = push_to_github(today_str, logger)
    if error:
        return 1
    return 0 if pushed_ok else 2


if __name__ == "__main__":
    sys.exit(main())
